### ISSUE TITLE
the footer doesn't entirely cover the moving image in the background

### ISSUE THREAD

**Issue by ronnyb29** [openconnectome/openconnectome.github.io#1]
ie. i can see a moving line with changing colors at the very bottom of the webpage, which is very distracting

**Comment by jovo** [comment]
yup, it is not in production yet.

On Wed, Jun 10, 2015 at 5:41 PM, ron boger <notifications@github.com> wrote:

>  ie. i can see a moving line with changing colors at the very bottom of
> the webpage, which is very distracting
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/1>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by j6k4m8** [comment]
(pull requests welcome)
