### ISSUE TITLE
the clickable pictures get much too small when transitioning to smaller screen sizes

### ISSUE THREAD

**Issue by ronnyb29** [openconnectome/openconnectome.github.io#11]
they should take up the full page. refer to image
![mri open connectome project - chromium_002](https://cloud.githubusercontent.com/assets/8752064/8243679/1d8b3890-15ce-11e5-902d-9462d7e8e61c.png)

**Comment by j6k4m8** [comment]
They're fully responsive...? Feel free to edit the breakpoints though

**Comment by jovo** [comment]
i agree that they are fine.
what do you mean they should take up the whole page.
they have an aspect ratio, they take up the whole width.

**Comment by j6k4m8** [comment]
(lol incognito mode)

**Comment by ronnyb29** [comment]
by full page i mean the pictures should fill up the page top to bottom,
instead of all the whitespace below the footer

**Comment by gkiar** [comment]
right, and as josh said, they have an aspect ratio that we are not going to
distort. so, what's your suggestion?

--
Greg Kiar <gkiar07@gmail.com>

**Comment by ronnyb29** [comment]
right. i just looked at the images and they aren't quite high res enough,
but i like how it's done on mobile with making each image take up a row

**Comment by jovo** [comment]
@ronnyb29 fix yourself or close please.

**Comment by ronnyb29** [comment]
hard to fix but it looks better at least when the footer sticks to the
bottom
added that functionality to a branch ron-dev, will pull request if you like
it

On Wed, Jun 24, 2015 at 1:08 PM, joshua vogelstein <notifications@github.com
