### ISSUE TITLE
>>> arrows don't line up perfectly with text on the buttons

### ISSUE THREAD

**Issue by ronnyb29** [openconnectome/openconnectome.github.io#2]
they should be shifted upwards by a few pixels

**Comment by jovo** [comment]
those buttons will be removed.
comments will start to be useful soon.

On Wed, Jun 10, 2015 at 5:42 PM, ron boger <notifications@github.com> wrote:

>  they should be shifted upwards by a few pixels
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/2>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by ronnyb29** [comment]
ok, will start commenting soon :(

**Comment by j6k4m8** [comment]
closing for now...
