### ISSUE TITLE
website background

### ISSUE THREAD

**Issue by willgray** [openconnectome/openconnectome.github.io#22]
I don't love the brain logo background.  Seems busy and less awesome than a dark gray.  Too much happening?  

I love the logo - just wondering if there is a way to simplify, with all the pictures/tiles happening too.

**Comment by gkiar** [comment]
+1. I suggest we use the same background without the logo - this already
exists on the Google drive, I anticipated it's need :)

**Comment by ronnyb29** [comment]
+1 keep it simpler. greg's background is perfect

**Comment by jovo** [comment]
@gkiar give me link to the background you like, and i'll try to include it.
alternately, you can try :)

**Comment by gkiar** [comment]
https://drive.google.com/file/d/0B_dAuemRqBb9cFJRZ2hEbXd6MEU/edit?usp=docslist_api

:)

**Comment by jovo** [comment]
hmm.  somehow, i don't seem to be able to get the background to not be the logo.

@j6k4m8 little help?
