### ISSUE TITLE
tell jovo how to see website in some dev mode locally

### ISSUE THREAD

**Issue by jovo** [openconnectome/openconnectome.github.io#24]

**Comment by ronnyb29** [comment]
will do

**Comment by j6k4m8** [comment]
Best way for stuff like this is to run `google-chrome --disable-web-security` (or `chromium-browser` if that's your cup of tea). It'll enable XSS and cross-domain loading (e.g. for LESS) — just remember to open another instance of chrome without that flag for your regular browsing. 

Then hit up `file:///path/to/html` to view. No server required!

**Comment by ronnyb29** [comment]
or Jordan will tell you ;p

**Comment by jovo** [comment]
this worked:
```open /Applications/Chromium.app --args --disable-web-security```
