### ISSUE TITLE
the titles of the squares are different heights, depending on how long the main text in the square is

### ISSUE THREAD

**Issue by jovo** [openconnectome/openconnectome.github.io#27]
this is true even when they are not highlight.
it is exacerbated when the window width is narrow.
i'm not sure how hard it is to 'fix' this, 
if not hard, let's fix.

**Comment by j6k4m8** [comment]
kinda hard. The best way to fix is to moderate the length of content;
otherwise, setting the `min-height` of the containing div to a larger value
will fix by making them uniform and equally not-vertically-centered.

**Comment by jovo** [comment]
fixed content length.
