### ISSUE TITLE
Slogan

### ISSUE THREAD

**Issue by willgray** [openconnectome/openconnectome.github.io#28]
Guys - thoughts on our catchy slogan.  

Right now we have:  

Overall OCP mission:
Lowering the barrier to entry into big data neuroscience by providing open source Web-services across a wide range of experimental modalities. 

I like short, sweet and memorable.  See Apple's "Think Different" and other campaigns.  

How about:  "Removing the barrier to entry for big data neuroscience."
Or maybe a positive version:  "Enabling big data neuroscience."

I think a longer version could go somewhere that has more description (modalities, etc), but would be nice to have a version that's short and sweet?  Discuss?

**Comment by jovo** [comment]
"Enabling" is the winner.
moved longer version down to modalities

**Comment by j6k4m8** [comment]
:+1: oooh that's *sharp*. Enabling big data neuroscience.
