### ISSUE TITLE
Web redirects

### ISSUE THREAD

**Issue by willgray** [openconnectome/openconnectome.github.io#29]
Followup to our earlier conversation.  Still trying to figure out what we are doing with redirects.  Seems like all openconnectome.github.io/XXX traffic is redirected to mri.ocp.me. 

Where is this rewrite rule?  On dsp29?  It's not on godaddy as far as I could tell.

Didn't understand @j6k4m8 's explanation about folders - seems like if we publish websites in gh-pages branches, that the sites all have a full url (e.g., openconnectome.github.io/manno) and don't have to be referenced as folders.

In any case, hoping for a way to publish my sphinx pages.  I can put them on EC2 or divshot or google docs if it's gonna be several days until we fix it.  Annoying but not fatal.

**Comment by jovo** [comment]
i don't know what the problem is.
openconnectome.github.io/manno redirects to mri.ocp.me/manno, which seems
to work fine.

On Sun, Jun 21, 2015 at 9:12 AM, William Gray <notifications@github.com>
wrote:

>  Followup to our earlier conversation. Still trying to figure out what we
> are doing with redirects. Seems like all openconnectome.github.io/XXX
> traffic is redirected to mri.ocp.me.
>
> Where is this rewrite rule? On dsp29? It's not on godaddy as far as I
> could tell.
>
> Didn't understand @j6k4m8 <https://github.com/j6k4m8> 's explanation
> about folders - seems like if we publish websites in gh-pages branches,
> that the sites all have a full url (e.g., openconnectome.github.io/manno)
> and don't have to be referenced as folders.
>
> In any case, hoping for a way to publish my sphinx pages. I can put them
> on EC2 or divshot or google docs if it's gonna be several days until we fix
> it. Annoying but not fatal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/29>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by willgray** [comment]
On Sun, Jun 21, 2015 at 3:40 PM, joshua vogelstein <notifications@github.com
> wrote:

> openconnectome.github.io/manno


I was just trying to show the format of the redirect.  An example of not
working is:
http://mri.ocp.me/vesicle/

I don't think this is my error (local copies all work fine), but don't know
why some work and some don't.

Best,
Will

**Comment by gkiar** [comment]
Cname file in the repo for redirects? Perhaps it exists in those that work
but not otherwise.

**Comment by willgray** [comment]
thanks - this worked.  (CNAME + .nojekyll)- got deleted along the way.  Still redirecting to mri.ocp.me, but obviously that will get fixed later.  Page works.
