### ISSUE TITLE
make m2g.io consistent with theme

### ISSUE THREAD

**Issue by jovo** [openconnectome/openconnectome.github.io#3]
@j6k4m8 greg and i have a plan, i expect it will not be difficult.
to discuss after you discuss with @willgray sphinx & readthedocs, which is far more important

**Comment by willgray** [comment]
I probably need more context here.  I'm building like 8 sphinx sites this
week and it's already hard/confusing.  Hoping this doesn't make it worse?

Or that I can ignore entirely and it's just a css update to the rtd theme?

Best,
Will

On Thu, Jun 18, 2015 at 3:50 PM, joshua vogelstein <notifications@github.com

**Comment by gkiar** [comment]
The second one. :) this shouldn't have any effect on functionality, and as
jovo said, we have a plan that we will explain when home.

**Comment by jovo** [comment]
correct.  only action here is potentially me and jordan,
definitely not will or greg.
no action from you guys regarding docs that are 'done' for at least 6
months, as promised :)

On Thu, Jun 18, 2015 at 10:06 AM, Greg Kiar <notifications@github.com>
wrote:

>  The second one. :) this shouldn't have any effect on functionality, and as
> jovo said, we have a plan that we will explain when home.
>
> On Jun 18, 2015 9:52 AM, "William Gray" <notifications@github.com> wrote:
>
> > I probably need more context here. I'm building like 8 sphinx sites this
> > week and it's already hard/confusing. Hoping this doesn't make it worse?
> >
> > Or that I can ignore entirely and it's just a css update to the rtd
> theme?
> >
> > Best,
> > Will
> >
> > On Thu, Jun 18, 2015 at 3:50 PM, joshua vogelstein <
> > notifications@github.com
> > > wrote:
> >
> > > @j6k4m8 <https://github.com/j6k4m8> greg and i have a plan, i expect
> it
> > > will not be difficult.
> > > to discuss after you discuss with @willgray <
> https://github.com/willgray
> > >
> > > sphinx & readthedocs, which is far more important
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/openconnectome/openconnectome.github.io/issues/3>.
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openconnectome/openconnectome.github.io/issues/3#issuecomment-113270927
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/3#issuecomment-113275028>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by jovo** [comment]
note that if we figure out how to do this for m2g, it should apply immediately to manno, i2g, cajal, vesicle, etc.
