### ISSUE TITLE
tools tile

### ISSUE THREAD

**Issue by willgray** [openconnectome/openconnectome.github.io#30]
@gkiar and I had a good talk last night - think it would be good to have a contribute tile and a tools tile, for each modality (and perhaps on the homepage too).

The tools tile would basically be a "list" of the different tools applicable for that domain/modality, and would link to our sphinx projects or external documentation (e.g., bigdata viewer) as appropriate.

Thoughts?

**Comment by jovo** [comment]
i currently have a 'contribute' and 'tools' section on the home page.
i haven't made the modalities pages yet, other than mri.

perhaps you guys make a mock up for mri of what you are envisioning?

On Monday, June 22, 2015, William Gray <notifications@github.com> wrote:

>  @gkiar <https://github.com/gkiar> and I had a good talk last night -
> think it would be good to have a contribute tile and a tools tile, for each
> modality (and perhaps on the homepage too).
>
> The tools tile would basically be a "list" of the different tools
> applicable for that domain/modality, and would link to our sphinx projects
> or external documentation (e.g., bigdata viewer) as appropriate.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/30>.
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by jovo** [comment]
note that the main page has 6 sections:

Access Viz Analytics Contribute Tools Info

i think all 'modality' pages should probably have all 6 as well.
note that 'analytics' means 'web-analytics', which is essentially all
web-services except viz.



On Monday, June 22, 2015, joshua vogelstein <joshuav@gmail.com> wrote:

> i currently have a 'contribute' and 'tools' section on the home page.
> i haven't made the modalities pages yet, other than mri.
>
> perhaps you guys make a mock up for mri of what you are envisioning?
>
> On Monday, June 22, 2015, William Gray <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>>  @gkiar <https://github.com/gkiar> and I had a good talk last night -
>> think it would be good to have a contribute tile and a tools tile, for each
>> modality (and perhaps on the homepage too).
>>
>> The tools tile would basically be a "list" of the different tools
>> applicable for that domain/modality, and would link to our sphinx projects
>> or external documentation (e.g., bigdata viewer) as appropriate.
>>
>> Thoughts?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/openconnectome/openconnectome.github.io/issues/30>.
>>
>
>
> --
> the glass is all full:  half water, half air.
> openconnecto.me, jovo.me, office hours
> <https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>
>
>

-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by j6k4m8** [comment]
Resolved in the neurodata.io repo.
