### ISSUE TITLE
navbar links don't show up anymore :(

### ISSUE THREAD

**Issue by jovo** [openconnectome/openconnectome.github.io#31]
i think i broke it.

**Comment by j6k4m8** [comment]
On `/mainpage` or root (mri)? On MRI, there aren't any. (They're commented, so we can always drop them back in.) On the mainpage, they have the class `hide-on-med-and-down`, which means that at somewhere around width=1000px, they show up — and are hidden on anything narrower. (`hide-on-small-only` does... well.. [what it says it does](http://materializecss.com/helpers.html#hiding).)

**Comment by jovo** [comment]
aha!  is it easy to make a little 'menu button' appear when the menu is hidden?

**Comment by j6k4m8** [comment]
Yep — akin to the sidebar we had earlier on /mri. I'll add it today!

**Comment by jovo** [comment]
word

**Comment by j6k4m8** [comment]
They show up again! Like a boss.

Like an offscreen-navigation boss. Fully-responsive offscreen-navigation boss.

**Comment by jovo** [comment]
:+1:

Q: is there a way to make a css something so that that behavior happens on all the sub-sites, eg, about.html?

**Comment by j6k4m8** [comment]
Not sure how gh handles templates, but we could try some underscore JS
templating for nav and footer if it's not handled internally. I'll check it
out.

**Comment by jovo** [comment]
does us getting a new web server change anything for you?

On Thursday, June 25, 2015, Jordan Matelsky <notifications@github.com>
wrote:

>  Not sure how gh handles templates, but we could try some underscore JS
> templating for nav and footer if it's not handled internally. I'll check it
> out.
> On Jun 24, 2015 6:55 PM, "joshua vogelstein" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > [image: :+1:]
> >
> > Q: is there a way to make a css something so that that behavior happens
> on
> > all the sub-sites, eg, about.html?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openconnectome/openconnectome.github.io/issues/31#issuecomment-115038628
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/31#issuecomment-115279334>
> .
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by j6k4m8** [comment]
Yup — once we can do our own templating (via php, JS, whatever) this'll be
a lot easier to manage.

**Comment by jovo** [comment]
ok. lets hold off on it until we get that up and running.

On Thursday, June 25, 2015, Jordan Matelsky <notifications@github.com>
wrote:

>  Yup — once we can do our own templating (via php, JS, whatever) this'll be
> a lot easier to manage.
>
> On Thu, Jun 25, 2015 at 11:12 AM, joshua vogelstein <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > does us getting a new web server change anything for you?
> >
> > On Thursday, June 25, 2015, Jordan Matelsky <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > Not sure how gh handles templates, but we could try some underscore JS
> > > templating for nav and footer if it's not handled internally. I'll
> check
> > it
> > > out.
> > > On Jun 24, 2015 6:55 PM, "joshua vogelstein" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > > wrote:
> > >
> > > > [image: :+1:]
> > > >
> > > > Q: is there a way to make a css something so that that behavior
> happens
> > > on
> > > > all the sub-sites, eg, about.html?
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/openconnectome/openconnectome.github.io/issues/31#issuecomment-115038628
> > > >
> > > > .
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/openconnectome/openconnectome.github.io/issues/31#issuecomment-115279334
> > >
> > > .
> > >
> >
> >
> > --
> > the glass is all full: half water, half air.
> > openconnecto.me, jovo.me, office hours
> > <
> >
> https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openconnectome/openconnectome.github.io/issues/31#issuecomment-115288256
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/31#issuecomment-115316003>
> .
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>
