### ISSUE TITLE
Main Page for all OCP documentation

### ISSUE THREAD

**Issue by kunallillaney** [openconnectome/openconnectome.github.io#35]
We should consider making docs.ocp.me as the main documentation page for all our docs. Then basically link off to other individual documentations.

**Comment by jovo** [comment]
that's a great idea!

On Thursday, June 25, 2015, Kunal L <notifications@github.com> wrote:

>  We should consider making docs.ocp.me as the main documentation page for
> all our docs. Then basically link off to other individual documentations.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/35>.
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by j6k4m8** [comment]
see ocpdocs -- name pending...

**Comment by jovo** [comment]
NeuroDataDocs

On Thu, Aug 27, 2015 at 2:48 PM, Jordan Matelsky <notifications@github.com>
wrote:

> see ocpdocs -- name pending...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/35#issuecomment-135520230>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York>

**Comment by willgray** [comment]
or just docs!

we should add the alias kunal suggests...

**Comment by jovo** [comment]
@willgray agreed.
docs.neurodata.io should be the meta-docs page.

**Comment by willgray** [comment]
Jordan can you do the redirect? 

target is openconnectome.github.io/docs
pending whatever is happening with our github repo.

**Comment by j6k4m8** [comment]
subdomain rewrites are probably Alex's domain, though I'll take a look.

**Comment by alexbaden** [comment]
I forgot how we did this with m2g. I don't think it was a CNAME....

**Comment by jovo** [comment]
the url is not particularly urgent, as long as the neurodatadocs page
exists and is linked to from the neurodata.io/about


On Thu, Aug 27, 2015 at 9:02 PM, Alex Baden <notifications@github.com>
wrote:

> I forgot how we did this with m2g. I don't think it was a CNAME....
>
> On Thu, Aug 27, 2015 at 8:58 PM Jordan Matelsky <notifications@github.com>
> wrote:
>
> > subdomain rewrites are probably Alex's domain, though I'll take a look.
> >
> > On Thu, Aug 27, 2015 at 7:53 PM William Gray <notifications@github.com>
> > wrote:
> >
> > > Reopened #35
> > > <https://github.com/openconnectome/openconnectome.github.io/issues/35
> >.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/openconnectome/openconnectome.github.io/issues/35#event-394586534
> > >
> > > .
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/openconnectome/openconnectome.github.io/issues/35#issuecomment-135594649
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/35#issuecomment-135595201>
> .
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=vk2j3ugqcitvq223g7ivvq4hqo%40group.calendar.google.com&ctz=America/New_York>

**Comment by gkiar** [comment]
as @alexbaden said, there was a cname file. @j6 if you need help, let me
know.

--
Greg Kiar <gkiar07@gmail.com>

On Thu, Aug 27, 2015 at 9:27 PM, joshua vogelstein <notifications@github.com

**Comment by j6k4m8** [comment]
Pretty certain CNAMEing is necessary but not sufficient — we also need a
server-side redirect through nginx on brainapps.

**Comment by jovo** [comment]
@j6k4m8 let me know if you need anything from any of us to make this happen.

**Comment by alexbaden** [comment]
We want docs.neurodata.io to go to where? @j6k4m8 and I will tag team.

 openconnectome.github.io/docs and neurodata.github.io/docs don't seem to work for me right now (404)

**Comment by willgray** [comment]
hmm...

https://github.com/openconnectome/docs
used to be:  github.com/openconnectome/ocpdocs
and this is also aliased:
github.com/openconnectome/ <http://github.com/openconnectome/ocpdocs>guide

This used to work fine.  I blame redirects?

Best,
Will

**Comment by alexbaden** [comment]
Useful: https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by j6k4m8** [comment]
Closing, move conversation to [here](https://github.com/openconnectome/ocp.me/issues/74).
