### ISSUE TITLE
Dynamic page for public OCP data map

### ISSUE THREAD

**Issue by kunallillaney** [openconnectome/openconnectome.github.io#36]
Another suggestions and I am not sure if this is under consideration. Is there a way we can build a pretty page which gives the user a look at all the possible public datasets we have. This should ideally replace the public data-map we have http://w.ocp.me/images. The page should load dynamically from some file or django models if possible which we can update as more tokens become public. This can act as a nice supplement to the exiting public tokens interface.

Note: This will not replace the private data-map we have.

**Comment by jovo** [comment]
yup, we *definitely* want that, which is why i asked earlier about finding all the tokens and stuff.  new the new branch and web-server operational to deploy that.

@alexbaden - we're gonna want to link to ocpviz for each project.

@j6k4m8 - we are gonna do this together, its gonna be awesome.

**Comment by alexbaden** [comment]
ocpviz works with all projects/tokens/channels using a URL call:

```ocp/viz/<<token>>/<<channel1:color1>>,<<channel2:color2>>, etc/center(res,x,y,z)/```

So if you download tokens/channels from OCP, this is easy.

**Comment by jovo** [comment]
@alexbaden - assuming data are on datascope and in new branch? or, it should work now for all public datasets?

**Comment by alexbaden** [comment]
Both, sort of. There are two options: 

1) ocpviz functions like CATMAID, where the user builds a VizProject and then adds VizLayers. For example, one could build a VizProject that contains all channels from one of the many Aratome datasets as VizLayers, or you could build a VizProject that contains some subset of Kristen's grouped anno layers as VizLayers. (in CATMAID a VizLayer is some hybrid between overlay and stack)

2) ocpviz automatically builds temporary VizProjects and VizLayers based on the URL (see above)

So, if data is in datascope and on the new branch, we use option 2 and run ocpviz primarily on dsp029 (the openconnecto.me webserver). If data is not in datascope and not on the new branch, we can build a VizProject / VizLayer for it. The url changes to something similar to the above, just with /project/ after /viz/

**Comment by jovo** [comment]
i see.

@alexbaden - can you put a list of url's, one per private project, somewhere accessible to me & @j6k4m8 ?
