### ISSUE TITLE
call to action/about section

### ISSUE THREAD

**Issue by ronnyb29** [openconnectome/openconnectome.github.io#38]
maybe a small section above all the pretty images would help people viewing the website understand what OCP is, thoughts?

**Comment by jovo** [comment]
yes, is coming, waiting for webserver to make further changes.
web-server should hopefully arrive this week,
operational next week.
website live NLT 7/31.

On Mon, Jul 13, 2015 at 7:13 PM, ron boger <notifications@github.com> wrote:

>  maybe a small section above all the pretty images would help people
> viewing the website understand what OCP is, thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/38>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>
