### ISSUE TITLE
footer doesn't stick to bottom on smaller screens

### ISSUE THREAD

**Issue by ronnyb29** [openconnectome/openconnectome.github.io#6]
need that sticky footer tho
![mri open connectome project - chromium_002](https://cloud.githubusercontent.com/assets/8752064/8243621/81f1df4c-15cd-11e5-8d5f-0f998150a620.png)

**Comment by j6k4m8** [comment]
yeah if you feel like trying to fix that, be my guest. That's like... kinda a tough thing

**Comment by jovo** [comment]
if @j6k4m8 says its hard, then its not worth anybody doing.
