### ISSUE TITLE
the support tab/picture looks clickable and changes to a clickable cursor, but isn't clickable making for minor user confusion

### ISSUE THREAD

**Issue by ronnyb29** [openconnectome/openconnectome.github.io#8]
i want to click it

**Comment by jovo** [comment]
<div class="square support onclick="nav('mailto:
contact@openconnecto.me')"">


failed.

fix it?

On Thu, Jun 18, 2015 at 12:21 PM, ron boger <notifications@github.com>
wrote:

>  i want to click it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/8>.
>



-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>

**Comment by j6k4m8** [comment]
Ah, didn't see the change of assignment. I'll take care of it then

**Comment by jovo** [comment]
I don't think this matters anymore

On Sunday, June 21, 2015, Jordan Matelsky <notifications@github.com> wrote:

>  Ah, didn't see the change of assignment. I'll take care of it then
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/openconnectome.github.io/issues/8#issuecomment-114004510>
> .
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
<https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York>
